<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Maps.Backup.Core\Maps.Backup.Core.csproj" />
    <ProjectReference Include="..\Maps.Backup.WorkFlowLib\Maps.Backup.WorkFlowLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="backup-config.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
